backup-united script update for mail notify

diff --git a/BackupUnited/backup-united b/BackupUnited/backup-united
--- a/BackupUnited/backup-united
+++ b/BackupUnited/backup-united
@@ -3,6 +3,8 @@
 WDIR=/usr/local/backup-united
 BACKUP_SCRIPTS=$WDIR/backup-scripts
 BACKUPS=$WDIR/backups
+MAILRECIPIENT=$WDIR/mail-recipient
+MAILMESSAGE=$WDIR/mail-message
 
 function pause(){
 local message="$@"
@@ -14,7 +16,7 @@ function show_menu(){
 date
 echo -e
 tput setaf 5
-echo "     BACKUP UNITED                                "
+echo "     BackupUnited                                "
 tput sgr0
 echo "   |---------------------------------------------|"
 echo "   | SMB Share Backup                            |"
@@ -31,9 +33,10 @@ tput setaf 5
 echo "     Mail Notification Settings                   "
 tput sgr0
 echo "   |---------------------------------------------|"
-echo "   | 4.Mail Settings     |                       |"
-echo "   | 5.Add    Recipient  |                       |"
-echo "   | 5.Remove Recipient  |                       |"
+echo "   | 30.Mail Settings     |                      |"
+echo "   | 31.Add    Recipient  |                      |"
+echo "   | 32.Remove Recipient  |                      |"
+echo "   | 33.Recipient List    |                      |"
 echo "   |---------------------------------------------|"
 tput setaf 9
 echo "                     -----------                  "
@@ -65,9 +68,9 @@ cat > /usr/local/backup-united/backup-scripts/$BACKUPNAME <<EOF
 if [ -d "$BACKUPPATH" ]; then
 rsync -avz /tmp/$BACKUPNAME /usr/local/backup-united/backups/$BACKUPNAME
 tar -czf /usr/local/backup-united/backups/$BACKUPNAME-"$JOCKER(date +%Y%m%d-%H%M).tar.gz" /usr/local/backup-united/backups/$BACKUPNAME
-echo "SUCCESS $BACKUPNAME" >> /usr/local/backup-united/mail-message
+echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
 else
-echo "FAILURE $BACKUPNAME" >> /usr/local/backup-united/mail-message
+echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
 fi
 EOF
 ;;
@@ -95,11 +98,11 @@ if [ -e "/tmp/$BACKUPNAME-mountok" ]
 then
 rsync -avz /tmp/$BACKUPNAME /usr/local/backup-united/backups/$BACKUPNAME
 tar -czf /usr/local/backup-united/backups/$BACKUPNAME-"$JOCKER(date +%Y%m%d-%H%M).tar.gz" /usr/local/backup-united/backups/$BACKUPNAME
-echo "$BACKUPNAME Backup Successfully taken" >> /usr/local/backup-united/mail-message
+echo "$BACKUPNAME Backup Successfully Taken" > /usr/local/backup-united/mail-message
 umount /tmp/$BACKUPNAME
 rm -rf /tmp/$BACKUPNAME-mountok
 else
-echo "$JOCKER(date +%Y%m%d-%H%M) - $BACKUPNAME Backup Failed" >> /usr/local/backup-united/mail-message
+echo "$BACKUPNAME Backup Failed" > /usr/local/backup-united/mail-message
 fi
 EOF
 BOARDMSG="$BACKUPNAME Backup Job Successfully Added"
@@ -137,26 +140,27 @@ pause
 }
 
 function mail_settings(){
-MAIL_ADDRESS=$(whiptail --title "Backup Name" --inputbox "Please Enter E-Mail Address" 10 60  3>&1 1>&2 2>&3)
-SMTP_URL=$(whiptail --title "Path of the Area" --inputbox "Please Enter SMTP Address-SMTP Port your Mailserver (smtps://user1@newdomain.com@mail.newdomain.com:465/)" 10 60  3>&1 1>&2 2>&3)
-SMTP_PASS=$(whiptail --title "Password" --password "Please Enter Password for E-Mail Address" 10 60  3>&1 1>&2 2>&3)
-###cat /dev/null > /etc/ssmtp/ssmtp.conf
-#----------------------------------------------------------------------
-# smtp address for example;
-# set smtp_url = "smtps://$USERNAME@$DOMAIN@mail.$DOMAIN:465/"
-# set smtp_url = "smtps://user1@newdomain.com@mail.newdomain.com:465/"
-#----------------------------------------------------------------------
-cat > ~/.muttrc <<EOF
-set from = "$MAIL_ADDRESS"
-set realname = "Backup United"
-set smtp_url = "$SMTP_URL"
-set smtp_pass = "$SMTP_PASS"
-set ssl_force_tls = yes
-unset ssl_starttls
+MAILADDR=$(whiptail --title "Backup Name" --inputbox "Please Enter E-Mail Address" 10 60  3>&1 1>&2 2>&3)
+SMTP=$(whiptail --title "Path of the Area" --inputbox "Please Enter SMTP Address-SMTP Port your Mailserver (smtp.gmail.com:587)" 10 60  3>&1 1>&2 2>&3)
+MAILUSER=$(whiptail --title "Username" --inputbox "Please Enter Username for E-Mail Address" 10 60  3>&1 1>&2 2>&3)
+MAILPASS=$(whiptail --title "Password" --inputbox "Please Enter Password for E-Mail Address" 10 60  3>&1 1>&2 2>&3)
+MAILDOMAIN=$(whiptail --title "Domain" --inputbox "Please Enter Domain for E-Mail Address (gmail.com,xyz.net etc)" 10 60  3>&1 1>&2 2>&3)
+cat /dev/null > /etc/ssmtp/ssmtp.conf
+cat > /etc/ssmtp/ssmtp.conf <<EOF
+root=$MAILADDR
+mailhub=$SMTP
+AuthUser=$MAILUSER
+AuthPass=$MAILPASS
+UseTLS=YES
+UseSTARTTLS=YES
+rewriteDomain=$MAILDOMAIN
+hostname=$HOSTNAME
+FromLineOverride=YES
 EOF
-###echo root:$MAILADDR:$SMTP
+echo root:$MAILADDR:$SMTP
 chfn -f 'backup-united' root
-###cp /usr/local/backup-united/notification/99-mail-sender /usr/local/backup-united/backup-scripts/
+
+cp /usr/local/backup-united/notification/99-mail-sender /usr/local/backup-united/backup-scripts/
 pause
 }
 
@@ -172,13 +176,29 @@ function backup_job_list(){
 	tput sgr0
 	ls $BACKUP_SCRIPTS
 	echo -e
+	
+	tput setaf 8	
+	echo "Backup Paths"
+	echo "---------------"
+	tput sgr0
+	ack "mount -t cifs" "$BACKUP_SCRIPTS" | cut -d " " -f4
+	echo -e
 	pause
+
+
 }
 
 function backup_now(){
-	### cp /usr/local/backup-united/notification/99-mail-sender /usr/local/backup-united/backup-scripts/
 	chmod +x $BACKUP_SCRIPTS/*
 	run-parts $BACKUP_SCRIPTS
+
+	NUMRECIPIENT=$(cat "$MAILRECIPIENT" | wc -l)
+	i=0
+	while [ "$i" -le $NUMRECIPIENT ]; do
+		RECIPIENT=$(ls -l | sed -n $i{p} "$MAILRECIPIENT")
+		cat $MAILMESSAGE | mutt -s "Backup United Notification" $RECIPIENT
+		i=$(( i + 1 ))
+	done
 	pause
 }
 
@@ -191,6 +211,22 @@ function backup_list(){
 	pause
 }
 
+function add_recipient(){
+	read -p "Email Adress : " EMAILADDRESS
+	echo "$EMAILADDRESS" >> $MAILRECIPIENT
+	pause
+}
+
+function recipient_list(){
+	tput setaf 8
+	echo "Mail Recipient List"
+	echo "-------------------"
+	tput sgr0
+	cat $MAILRECIPIENT
+	echo -e
+	pause
+}
+
 function read_input(){
 local c
 read -p "Please choose from Menu numbers " c
@@ -198,11 +234,10 @@ case $c in
 1)	add_backup;;
 2)	del_backup;;
 3)	backup_job_list;;
-5)      clean_backup;;
 10)	backup_now;;
 11)	backup_list;;
-8)	mail_settings;;
-9)	add_recipients;;
+30)	add_recipient;;
+33)	recipient_list;;
 99)	exit 0 ;;
 *)	
 echo "Please choose from Menu numbers"
