check and install req. packages

diff --git a/BackupUnited/backup-united b/BackupUnited/backup-united
--- a/BackupUnited/backup-united
+++ b/BackupUnited/backup-united
@@ -1,41 +1,49 @@
 #!/bin/bash
 
-#-----------------------------------------------
-# installation
-#-----------------------------------------------
-# apt-get -y install rdiff-backup rsync ssmtp mutt
-# apt-get -y install cifs-utils smbclient
-# apt-get -y install tree ack
-# mkdir -p /usr/local/backup-united/backup
-# mkdir -p /usr/local/backup-united/backup-scripts
-# mkdir -p /usr/local/backup-united/backups
-# cp mail-sender.sh /usr/local/backup-united/
-#
-#-----------------------------------------------
-# /usr/local/backup-united/mail-sender.sh
-#-----------------------------------------------
-# #!/bin/bash
-#WDIR=/usr/local/backup-united
-#BACKUP_SCRIPTS=$WDIR/backup-scripts
-#BACKUPS=$WDIR/backups
-#MAILRECIPIENT=$WDIR/mail-recipient
-#MAILMESSAGE=$WDIR/mail-message
-#
-#NUMRECIPIENT=$(cat "$MAILRECIPIENT" | wc -l)
-#i=1
-#while [ "$i" -le $NUMRECIPIENT ]; do
-#        RECIPIENT=$(ls -l | sed -n $i{p} "$MAILRECIPIENT")
-#        cat $MAILMESSAGE | mutt -s "Backup United Notification" $RECIPIENT
-#        i=$(( i + 1 ))
-#done
-#-----------------------------------------------
-
 WDIR=/usr/local/backup-united
 BACKUP_SCRIPTS=$WDIR/backup-scripts
 BACKUPS=$WDIR/backups
 MAILRECIPIENT=$WDIR/mail-recipient
 MAILMESSAGE=$WDIR/mail-message
 MAILSENDER=$WDIR/mail-sender.sh
+
+#-----------------------------------------------
+# check & install required packages
+#-----------------------------------------------
+if ! [ -x "$(command -v rsync)" ] \
+	|| ! [ -x "$(command -v rdiff-backup)" ] \
+	|| ! [ -x "$(command -v ssmtp)" ] \
+	|| ! [ -x "$(command -v mutt)" ] \
+	|| ! [ -x "$(command -v smbclient)" ] \
+	|| ! [ -x "$(command -v tree)" ] \
+	|| ! [ -x "$(command -v ack)" ]; then
+		echo "-------------------------------"
+		echo "installing missing packages..  "
+		echo "-------------------------------"
+		echo -e
+		apt-get -y install rsync rdiff-backup ssmtp mutt
+		apt-get -y install cifs-utils smbclient
+		apt-get -y install tree ack
+
+		mkdir -p /usr/local/backup-united/backup
+		mkdir -p /usr/local/backup-united/backup-scripts
+		mkdir -p /usr/local/backup-united/backups
+fi
+
+cat > "$WDIR/mail-sender.sh" <<EOF
+#!/bin/bash
+MAILRECIPIENT=$WDIR/mail-recipient
+MAILMESSAGE=$WDIR/mail-message
+
+NUMRECIPIENT=$(cat "$MAILRECIPIENT" | wc -l)
+i=1
+while [ "$i" -le $NUMRECIPIENT ]; do
+        RECIPIENT=$(ls -l | sed -n $i{p} "$MAILRECIPIENT")
+        cat $MAILMESSAGE | mutt -s "Backup United Notification" $RECIPIENT
+        i=$(( i + 1 ))
+done
+EOF
+chmod +x $WDIR/mail-sender.sh
 
 function pause(){
 local message="$@"
